/** Seed data transcribed verbatim from BUILD.md §2 "Seed data" table. */
export const venturesSeed = [
  {
    name: 'House',
    slug: 'house',
    zone: 'neutral' as const,
    order: 0,
    palette: { key: '#6A7688', hi: '#8CA0FF', deep: '#161B23', lift: '#F1F4F7', on: '#FFFFFF' },
    proposed: false,
  },
  {
    name: 'Memrey',
    slug: 'memrey',
    zone: 'engineering' as const,
    order: 1,
    palette: { key: '#5B2470', hi: '#FF8A3D', deep: '#2A0F3A', lift: '#F4ECF8', on: '#FFFFFF' },
    proposed: false,
  },
  {
    name: 'Rotavox',
    slug: 'rotavox',
    zone: 'engineering' as const,
    order: 2,
    palette: { key: '#0F7A52', hi: '#38D08C', deep: '#05261A', lift: '#E9F7F0', on: '#FFFFFF' },
    proposed: true,
  },
  {
    name: 'Soldera',
    slug: 'soldera',
    zone: 'engineering' as const,
    order: 3,
    palette: { key: '#C81B7A', hi: '#FF6CB6', deep: '#2A0620', lift: '#FDE9F4', on: '#FFFFFF' },
    proposed: true,
  },
  {
    name: 'Bolt',
    slug: 'bolt',
    zone: 'media' as const,
    order: 4,
    palette: { key: '#FF3B1E', hi: '#FF7A45', deep: '#1A0904', lift: '#FFEDE9', on: '#1A0904' },
    proposed: false,
  },
  {
    name: 'Signal',
    slug: 'signal',
    zone: 'media' as const,
    order: 5,
    palette: { key: '#00E8D0', hi: '#7DF7EA', deep: '#04201E', lift: '#E4FBF8', on: '#04211E' },
    proposed: false,
  },
  {
    name: 'Shadowcat',
    slug: 'shadowcat',
    zone: 'media' as const,
    order: 6,
    palette: { key: '#E2A03C', hi: '#FFD08A', deep: '#120C04', lift: '#FBF3E5', on: '#241703' },
    proposed: true,
  },
]
